### ISSUE TITLE
contact status not updated

### ISSUE THREAD

**Issue by bosjp** [kesteraernoudt/dobiss#109]
hello,

long time ago, hope you are doing well ?

I made an upgrade of DOBISS nxt (actually on [DOBISS NXT 3.20-1])
I am in the last version for Home Assistant

I have 2 modules of contacts and in the past everything worked perfectly but since few days/weeks it's not the case anymore (I can't confirm after which upgrade problem appears)
for somes windows/doors open or close, the sensor work and the status is changed but it's not the case for some other windows/doors. 
in the application (webserever NXT), the status is changed correctly but not in HA.
if I restart the integration when the status of a window/door is changed, the correct status appears in HA only after the restart. that means if I need the right status, I need to restart the integration to be sure.

## Version of the custom_component

If you are unsure about the version check the const.py file.
--> no reference about the version in const.py

## Configuration

```yaml
Add your logs here.
```

## Debug log

```text

Add your logs here.

```

**Comment by kesteraernoudt** [comment]
Could you try with the dev branch? You probably need to reinstall the dobiss integration, and then select the dev branch instead of a release. I did make some updates to be better compatible with the latest dobiss NXT release, and I don't have issues anymore. So i'd like to understand if this fixes these for you as well...

**Comment by bosjp** [comment]
thanks for your answer..... I will do it asap
I keep you posted

**Comment by bosjp** [comment]
I delete the integration and try to reinstall it, but where can i select de dev branch into the GUI of HA ?

**Comment by kesteraernoudt** [comment]
in HACS, you can select the release or development branch

**Comment by kesteraernoudt** [comment]
To be more specific, in HACS, when you open the dobiss integration, you click on the 3 dots top right, and select 'redownload'. There you can pick the version, and dev is one of them:
![image](https://user-images.githubusercontent.com/1177997/194526626-1c2bb5ff-93de-4ffc-810e-0a60ceeb59f9.png)

**Comment by bosjp** [comment]
hello,

done but the problem is still there

**Comment by kesteraernoudt** [comment]
ok, so we need to debug this indeed. Do you know which contacts don't work? Is it from one module, or is it a mix?

**Comment by bosjp** [comment]
yes for sure ....

first of all, the three contacts from the NXT server himself....

**Comment by kesteraernoudt** [comment]
if I understand correctly, the inputs on the NXT module itself don't work for you, but the external module work fine?

I only have inputs on an external module, so I can't really reproduce this... I'll have a look at adding more debug info - if you could help me get the logs for those, that would be great

**Comment by bosjp** [comment]
![IMG_3986 Small](https://user-images.githubusercontent.com/76811225/194575950-fc380cb9-be3b-46c9-82ce-e23ff36dfe9b.jpeg)

**Comment by bosjp** [comment]
hello,

it works ...... you are the best ! rootcause was a change into the API of Dobiss ?

thx a lot,

jean-pierre

**Comment by kesteraernoudt** [comment]
I do get a different message from the NXT server now indeed, but I asked for clarification if it's a bug or if it's also a valid message. I've implemented a workaround which now also accepts that message, and will see what they come back with...

**Comment by kesteraernoudt** [comment]
I've released v1.6 with the fix included - closing this issue
