### ISSUE TITLE
Covers manual stop

### ISSUE THREAD

**Issue by groovydc** [kesteraernoudt/dobiss#153]
Hello, I successfully implemented dobiss in home assistant. But I have a problem with my shutters. I can't stop the shutters when they are opening. Only up or down. In dobiss you have to click a 2nd time on the same button then the roller shutter stops, but in HA this does not work. There is a stop button but it does not work either. hopefully someone knows a solution

**Comment by kesteraernoudt** [comment]
did you configure timed covers, or not? If not, i haven't gotten a foolproof method to figure out how to stop a cover. In dobiss, there are from what I can tell 2 types of covers: some use pulses, some have to be kept active during the whole movement. In my system, those that use pulses have specific names - ending in 'op' and 'neer', and 'open' and 'dicht'. I do have a note in my code to make this flexible, but for now that's not yet done... What are the names of the open and close or up and down switches in dobiss? Maybe I can add some quick fix? Making it flexible is a bit more work :)

        # do some hacky check to see which type it is --> todo: make this flexible!
        # from dobiss: if it is a shade, up and down have the same name
        # if it is a velux shade, up and down end in 'op' and 'neer'
        # if it is a velux window, up and down end in 'open' and 'dicht'

**Comment by groovydc** [comment]
No i don't have timed covers.  From what i know my shutters are installed wen they put the windows in my house. in dobiss it's only up or down. if i open a shutter and not want it all up i press up again and then they stop in dobiss.

**Comment by groovydc** [comment]
At my windows i have no switches

**Comment by kesteraernoudt** [comment]
What’s the name of the entities in ha for the push buttons?On 24 Aug 2023, at 18:39, groovydc ***@***.***> wrote:﻿
At my windows i have no switches

**Comment by groovydc** [comment]
example: cover.bureau ?

**Comment by groovydc** [comment]
Up dobiss group
Rolluiken
Up name
Bureau op
Up address
3
Up channel
0
Up type
8
Up tags
3.1
Up icons ID
3
Up dimmable
Onbekend
Up settings
locks:
- 1
- null
readonly: null
pincode: null
Down dobiss group
Rolluiken
Down name
Bureau neer
Down address
3
Down channel
1
Down type
8
Down tags
3.2
Down icons ID
4
Down dimmable
Onbekend
Down settings
locks:
- 0
- null
readonly: null
pincode: null
Last up
true
Delta
0

**Comment by kesteraernoudt** [comment]
can you enable debug logging (see https://github.com/kesteraernoudt/dobiss#readme), start the cover, and try to stop it. Then send the debug log to me so I can analyze what's going on?

**Comment by groovydc** [comment]
> can you enable debug logging (see https://github.com/kesteraernoudt/dobiss#readme), start the cover, and try to stop it. Then send the debug log to me so I can analyze what's going on?

yes i added the code to my configuration.yaml now where can i find the logs?

**Comment by kesteraernoudt** [comment]
you have to restart home assistant when you change the config file. But then it's the standard home assistant log file, which is in the configuration folder...

**Comment by groovydc** [comment]
finaly time for home assistant needed to do a lot of updates and finaly got debug log running

this here was the error in HA

> #Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 21:00:42 (9 occurrences)
Last logged: 21:27:17

[140379110926400] Passing coroutines is forbidden, use tasks explicitly.
[140378765601216] Passing coroutines is forbidden, use tasks explicitly.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/dobiss/cover.py", line 246, in async_stop_cover
    await wait([self._up.turn_on(), self._down.turn_on()])
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 425, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.

**Comment by brandsb** [comment]
I also experience this issue. Is there an update yet?
```
Logger: homeassistant.components.websocket_api.http.connection
Bron: components/websocket_api/commands.py:239
integratie: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:06:28 (1 gebeurtenissen)
Laatst gelogd: 20:06:28

[140610721810624] Passing coroutines is forbidden, use tasks explicitly.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/dobiss/cover.py", line 248, in async_stop_cover
    await wait([self._up.turn_off(), self._down.turn_off()])
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 461, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.

```

**Comment by brandsb** [comment]
#185 
Submitted a PR to fix this

**Comment by kesteraernoudt** [comment]
Thanks! I merged it - let me know if it works for you now!

**Comment by brandsb** [comment]
I updated the hacs integration with the dev version. Charges are tested and working as expected.

@groovydc if you’re still following the thread… with summer incoming it’s nice to be able to stop the covers half way down 😁
