### ISSUE TITLE
Add an option to update the host ip at runtime

### ISSUE THREAD

**Issue by frederik14** [kesteraernoudt/dobiss#201]
Living in Belgium and having a Telenet router I am unable to have a dhcp reservation setup for the dobiss nxt server.

Would it be possible to update the dobiss sever IP address as an option when the integration is already setup? Now the ip adress is changing if the dobiss server is rebooted.

Tried dobiss.local already, but that was not working in a reliable way.

Thanks for the help!

**Comment by kesteraernoudt** [comment]
This would be quite difficult to implement the way this is handled now - you could remove the integration and add it again with the new Ip address - the name of the devices and entities should remain the same...

**Comment by kesteraernoudt** [comment]
I'm gonna close this as there is a workaround and it's not really feasible to implement...
