### ISSUE TITLE
NXT server V3.8 websocket connection is failing

### ISSUE THREAD

**Issue by frederik14** [kesteraernoudt/dobiss#208]
## Version of the custom_component

latest

## Configuration

Logger: dobissapi.dobissapi
Source: /usr/local/lib/python3.12/site-packages/dobissapi/dobissapi.py:890
First occurred: 11:21:49 PM (27 occurrences)
Last logged: 11:26:11 PM

Failed to connect, waiting a bit before retrying: ClientResponseError(RequestInfo(url=URL('ws://192.168.0.178/sockets/api'), method='GET', headers=<CIMultiDictProxy('Host': '192.168.0.178', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsImV4cGlyZXNJbiI6IjI0aCIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXlfYXBwbGljYXRpb24ifQ.LbZcDjCVcBy3dXOUDwp-xLFN8fZHl6fK6HNCFSXR348', 'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Sec-WebSocket-Version': '13', 'Sec-WebSocket-Key': 'Xp3u3ZPv9APsQ8j9qd6qxQ==', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, br', 'User-Agent': 'Python/3.12 aiohttp/3.10.10')>, real_url=URL('ws://192.168.0.178/sockets/api')), (), status=426, message='No Sec-WebSocket-Protocols requested supported', headers=<CIMultiDictProxy('Server': 'nginx/1.18.0', 'Date': 'Wed, 13 Nov 2024 22:25:31 GMT', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Upgrade': 'websocket', 'Sec-WebSocket-Version': '13', 'Sec-WebSocket-Protocol': 'wamp', 'X-Powered-By': 'Ratchet/0.4.4')>)

## Describe the bug

Request to change light state works, but all the feedback via the websocket is failing

```

**Comment by kesteraernoudt** [comment]
This seems to be the same as https://github.com/kesteraernoudt/dobiss/issues/202 - can you check if the provided solution there works?

**Comment by frederik14** [comment]
Thanks, the new version worked
